server:
  port: "8080"
data_source: #The user and password must be passed through the DB_USER and DB_PASSWORD env.
  host: "127.0.0.1"
  port: 5432
  db: "mydb"
  max_connection: 20
  min_connection: 5
  connection_life_time: "1h"
logger:
  level: "DEBUG"

