// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/signup": {
            "post": {
                "description": "Registering a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/plain"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Registering a new user",
                "parameters": [
                    {
                        "description": "Account information for signup",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Information about the user's account after successful registration",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad json in request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "A user already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.CreateUserRequest": {
            "description": "User account information for registration",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@email.com"
                },
                "lastname": {
                    "type": "string",
                    "example": "Doe"
                },
                "name": {
                    "type": "string",
                    "example": "John"
                },
                "nickname": {
                    "type": "string",
                    "example": "Johny1"
                },
                "password": {
                    "type": "string",
                    "example": "mySuperPass"
                },
                "phone": {
                    "type": "integer",
                    "example": 79990001122
                }
            }
        },
        "dtos.CreateUserResponse": {
            "description": "Information about the user's account after successful registration",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "20060102 03:04:05"
                },
                "user_type": {
                    "type": "string",
                    "example": "USER"
                },
                "uuid": {
                    "type": "string",
                    "example": "16763be4-6022-406e-a950-fcd5018633ca"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "IstokAuthorization",
	Description:      "Authorization service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
